<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>SQB.Auth.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SQB.Auth.Domain\SQB.Auth.Domain.csproj" />
      <ProjectReference Include="..\SQB.Shared\SQB.Shared.csproj" />
    </ItemGroup>

</Project>
