using Dapper;
using FluentAssertions;
using Microsoft.Extensions.Options;
using Npgsql;
using SQB.Auth.Domain.Entities;
using SQB.Auth.Domain.Models;
using SQB.Auth.Infrastructure.Repositories;
using Testcontainers.PostgreSql;

namespace SQB.Auth.Tests;

public class DapperUserStoreTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _dbContainer = new PostgreSqlBuilder()
        .WithImage("postgres:15-alpine")
        .Build();

    private DapperUserStore _sut;

    private string _connectionString;

    public async Task InitializeAsync()
    {
        await _dbContainer.StartAsync();
        _connectionString = _dbContainer.GetConnectionString();

        var options = Options.Create(new IdentityStoreOptions { ConnectionString = _connectionString });
        _sut = new DapperUserStore(options);

        await InitializeDatabaseAsync();
    }

    public async Task DisposeAsync()
    {
        await _dbContainer.DisposeAsync();
    }

    private async Task InitializeDatabaseAsync()
    {
        // Modified DDL: removed "owner to administrator" statements as we are running as superuser in container
        const string ddl = """
            -------------------- users --------------------
            create table users
            (
                Id                     uuid not null
                    constraint pk_users
                        primary key,
                UserName              varchar(256),
                NormalizedUserName   varchar(256),
                Email                  varchar(150)             not null,
                NormalizedEmail       varchar(256),
                EmailConfirmed        boolean                  not null,
                PasswordHash          text,
                SecurityStamp         text,
                ConcurrencyStamp      text,    
                PhoneNumber           varchar(30),
                PhoneNumberConfirmed boolean,
                TwoFactorEnabled     boolean                  not null,
                LockoutEnd            timestamp with time zone,
                LockoutEnabled        boolean                  not null,
                AccessFailedCount    integer                  not null,
                CreatedAt             timestamp with time zone not null,
                UpdatedAt             timestamp with time zone not null
            );

            create index email_index
                on users (NormalizedEmail);

            create unique index user_name_index
                on users (NormalizedUserName);

            -------------------- roles --------------------
            create table roles
            (
                Id                integer generated by default as identity
                    constraint pk_roles
                        primary key,
                Name              varchar(256),
                NormalizedName   varchar(256),
                ConcurrencyStamp text
            );

            create unique index role_name_index
                on roles (NormalizedName);

            -------------------- user roles --------------------
            create table user_roles
            (
                UserId uuid not null
                    constraint fk_user_roles_users_user_id
                        references users(Id)
                        on delete cascade,
                RoleId integer not null
                    constraint fk_user_roles_roles_role_id
                        references roles(Id)
                        on delete cascade,
                constraint pk_user_roles
                    primary key (UserId, RoleId)
            );

            create index ix_user_roles_role_id
                on user_roles (RoleId);


            ------------------refresh-tokens--------------------
            create table refresh_tokens
            (
                Id integer generated by default as identity
                    constraint pk_refresh_tokens
                        primary key,
                Token text                                      not null,
                Expires timestamp with time zone                not null,
                CreatedAt timestamp with time zone             not null,
                CreatedByIp text                              not null,
                Revoked timestamp with time zone,
                RevokedByIp text,
                ReplacedByToken text,
                UserId uuid not null
                    constraint fk_refresh_tokens_users
                        references users(Id)
                        on delete cascade
            );

            create unique index ix_refresh_tokens_token
                on refresh_tokens(Token);
            """;

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();
        await connection.ExecuteAsync(ddl);

        // Seed some roles
        await connection.ExecuteAsync("insert into roles (Name, NormalizedName) values ('Admin', 'ADMIN'), ('User', 'USER')");
    }

    [Fact]
    public async Task CreateAsync_ShouldCreateUser_WhenUserIsValid()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "testuser",
            NormalizedUserName = "TESTUSER",
            Email = "test@example.com",
            NormalizedEmail = "TEST@EXAMPLE.COM",
            EmailConfirmed = true,
            SecurityStamp = "stamp",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        // Act
        var result = await _sut.CreateAsync(user, CancellationToken.None);

        // Assert
        result.Succeeded.Should().BeTrue();

        // Verify in DB
        await using var connection = new NpgsqlConnection(_connectionString);
        var dbUser = await connection.QuerySingleOrDefaultAsync<User>("select * from users where id = @Id", new { user.Id });
        dbUser.Should().NotBeNull();
        dbUser.UserName.Should().Be(user.UserName);
    }

    [Fact]
    public async Task CreateAsync_ShouldFail_WhenUserDuplicate()
    {
        // Arrange
        var user1 = new User
        {
            Id = Guid.NewGuid(),
            UserName = "duplicate",
            NormalizedUserName = "DUPLICATE",
            Email = "dup@example.com",
            NormalizedEmail = "DUP@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        await _sut.CreateAsync(user1, CancellationToken.None);

        var user2 = new User
        {
            Id = Guid.NewGuid(),
            UserName = "duplicate",
            NormalizedUserName = "DUPLICATE",  // Duplicate username
            Email = "other@example.com",
            NormalizedEmail = "OTHER@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        // Act
        var result = await _sut.CreateAsync(user2, CancellationToken.None);

        // Assert
        result.Succeeded.Should().BeFalse();
        result.Errors.Should().Contain(e => e.Code == "UniqueViolation");
    }

    [Fact]
    public async Task FindByNameAsync_ShouldReturnUser_WhenUserExists()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "findme",
            NormalizedUserName = "FINDME",
            Email = "findme@example.com",
            NormalizedEmail = "FINDME@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        await _sut.CreateAsync(user, CancellationToken.None);

        // Act
        var result = await _sut.FindByNameAsync("FINDME", CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.Id.Should().Be(user.Id);
    }

    [Fact]
    public async Task FindByEmailAsync_ShouldReturnUser_WhenUserExists()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "findemail",
            NormalizedUserName = "FINDEMAIL",
            Email = "findemail@example.com",
            NormalizedEmail = "FINDEMAIL@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        await _sut.CreateAsync(user, CancellationToken.None);

        // Act
        var result = await _sut.FindByEmailAsync("FINDEMAIL@EXAMPLE.COM", CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.Id.Should().Be(user.Id);
    }

    [Fact]
    public async Task UpdateAsync_ShouldUpdateUser_WhenConcurrencyStampMatches()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "update",
            NormalizedUserName = "UPDATE",
            Email = "update@example.com",
            NormalizedEmail = "UPDATE@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        var concurrencyStampBefore = user.ConcurrencyStamp;
        await _sut.CreateAsync(user, CancellationToken.None);

        user.PhoneNumber = "1234567890";

        // Act
        var result = await _sut.UpdateAsync(user, CancellationToken.None);

        // Assert
        result.Succeeded.Should().BeTrue();

        // Verify
        var updatedUser = await _sut.FindByIdAsync(user.Id.ToString(), CancellationToken.None);
        updatedUser.PhoneNumber.Should().Be("1234567890");
        updatedUser.ConcurrencyStamp.Should().NotBe(concurrencyStampBefore);
    }

    [Fact]
    public async Task UpdateAsync_ShouldFail_WhenConcurrencyStampMismatch()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "concurrent",
            NormalizedUserName = "CONCURRENT",
            Email = "concurrent@example.com",
            NormalizedEmail = "CONCURRENT@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        await _sut.CreateAsync(user, CancellationToken.None);

        // Simulate concurrent update by changing stamp in memory but not DB or vice versa
        // Actually, CreateAsync updates user.ConcurrencyStamp. Let's start a second instance.
        var userCopy = await _sut.FindByIdAsync(user.Id.ToString(), CancellationToken.None);

        // Update original
        await _sut.UpdateAsync(user, CancellationToken.None);

        // Try to update copy which has old stamp
        userCopy.PhoneNumber = "00000000";

        // Act
        var result = await _sut.UpdateAsync(userCopy, CancellationToken.None);

        // Assert
        result.Succeeded.Should().BeFalse();
        result.Errors.Should().Contain(e => e.Code == "ConcurrencyFailure");
    }

    [Fact]
    public async Task DeleteAsync_ShouldDeleteUser_WhenExists()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "delete",
            NormalizedUserName = "DELETE",
            Email = "delete@example.com",
            NormalizedEmail = "DELETE@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        await _sut.CreateAsync(user, CancellationToken.None);

        // Act
        var result = await _sut.DeleteAsync(user, CancellationToken.None);

        // Assert
        result.Succeeded.Should().BeTrue();
        var deletedUser = await _sut.FindByIdAsync(user.Id.ToString(), CancellationToken.None);
        deletedUser.Should().BeNull();
    }

    [Fact]
    public async Task AddToRoleAsync_ShouldAddRole_WhenUserAndRoleExist()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "roleuser",
            NormalizedUserName = "ROLEUSER",
            Email = "role@example.com",
            NormalizedEmail = "ROLE@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        await _sut.CreateAsync(user, CancellationToken.None);

        // AddToRole just adds to in-memory collection in DapperUserStore logic (implied by typical Identity stores), 
        // but DapperUserStore.UpdateAsync persists it. Let's check implementation.
        // DapperUserStore.AddToRoleAsync: adds to user.RolesToAdd list.
        // DapperUserStore.UpdateAsync: iterates RolesToAdd and inserts into DB.

        await _sut.AddToRoleAsync(user, "Admin", CancellationToken.None);

        // Act
        var result = await _sut.UpdateAsync(user, CancellationToken.None);

        // Assert
        result.Succeeded.Should().BeTrue();

        var roles = await _sut.GetRolesAsync(user, CancellationToken.None);
        roles.Should().Contain("Admin");
    }

    [Fact]
    public async Task GetUserIdAsync_ShouldReturnUserId_WhenUserIsValid()
    {
        // Arrange
        var user = new User { Id = Guid.NewGuid() };

        // Act
        var result = await _sut.GetUserIdAsync(user, CancellationToken.None);

        // Assert
        result.Should().Be(user.Id.ToString());
    }

    [Fact]
    public async Task GetUserIdAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.GetUserIdAsync(null!, CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task GetUserNameAsync_ShouldReturnUserName_WhenUserIsValid()
    {
        // Arrange
        var user = new User { UserName = "testuser" };

        // Act
        var result = await _sut.GetUserNameAsync(user, CancellationToken.None);

        // Assert
        result.Should().Be("testuser");
    }

    [Fact]
    public async Task GetUserNameAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.GetUserNameAsync(null!, CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task SetUserNameAsync_ShouldSetUserName_WhenUserIsValid()
    {
        // Arrange
        var user = new User();

        // Act
        await _sut.SetUserNameAsync(user, "newuser", CancellationToken.None);

        // Assert
        user.UserName.Should().Be("newuser");
    }

    [Fact]
    public async Task SetUserNameAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.SetUserNameAsync(null!, "newuser", CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task GetNormalizedUserNameAsync_ShouldReturnNormalizedName_WhenUserIsValid()
    {
        // Arrange
        var user = new User { NormalizedUserName = "TESTUSER" };

        // Act
        var result = await _sut.GetNormalizedUserNameAsync(user, CancellationToken.None);

        // Assert
        result.Should().Be("TESTUSER");
    }

    [Fact]
    public async Task GetNormalizedUserNameAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.GetNormalizedUserNameAsync(null!, CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task SetNormalizedUserNameAsync_ShouldSetNormalizedName_WhenUserIsValid()
    {
        // Arrange
        var user = new User();

        // Act
        await _sut.SetNormalizedUserNameAsync(user, "TESTUSER", CancellationToken.None);

        // Assert
        user.NormalizedUserName.Should().Be("TESTUSER");
    }

    [Fact]
    public async Task SetNormalizedUserNameAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.SetNormalizedUserNameAsync(null!, "TESTUSER", CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task FindByIdAsync_ShouldReturnUser_WhenUserExists()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "findbyid",
            NormalizedUserName = "FINDBYID",
            Email = "find@example.com",
            NormalizedEmail = "FIND@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        await _sut.CreateAsync(user, CancellationToken.None);

        // Act
        var result = await _sut.FindByIdAsync(user.Id.ToString(), CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.Id.Should().Be(user.Id);
    }

    [Fact]
    public async Task FindByIdAsync_ShouldReturnNull_WhenUserDoesNotExist()
    {
        // Act
        var result = await _sut.FindByIdAsync(Guid.NewGuid().ToString(), CancellationToken.None);

        // Assert
        result.Should().BeNull();
    }

    [Fact]
    public async Task FindByIdAsync_ShouldReturnNull_WhenIdIsInvalidFormat()
    {
        // Act
        var result = await _sut.FindByIdAsync("invalid-guid", CancellationToken.None);

        // Assert
        result.Should().BeNull();
    }
    //
    [Fact]
    public async Task SetPasswordHashAsync_ShouldSetHash_WhenUserIsValid()
    {
        // Arrange
        var user = new User();

        // Act
        await _sut.SetPasswordHashAsync(user, "hash", CancellationToken.None);

        // Assert
        user.PasswordHash.Should().Be("hash");
    }

    [Fact]
    public async Task SetPasswordHashAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.SetPasswordHashAsync(null!, "hash", CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task GetPasswordHashAsync_ShouldReturnHash_WhenUserHasPassword()
    {
        // Arrange
        var user = new User { PasswordHash = "hash" };

        // Act
        var result = await _sut.GetPasswordHashAsync(user, CancellationToken.None);

        // Assert
        result.Should().Be("hash");
    }

    [Fact]
    public async Task GetPasswordHashAsync_ShouldReturnNull_WhenUserHasNoPassword()
    {
        // Arrange
        var user = new User();

        // Act
        var result = await _sut.GetPasswordHashAsync(user, CancellationToken.None);

        // Assert
        result.Should().BeNull();
    }

    [Fact]
    public async Task GetPasswordHashAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.GetPasswordHashAsync(null!, CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task HasPasswordAsync_ShouldReturnTrue_WhenUserHasPassword()
    {
        // Arrange
        var user = new User { PasswordHash = "hash" };

        // Act
        var result = await _sut.HasPasswordAsync(user, CancellationToken.None);

        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public async Task HasPasswordAsync_ShouldReturnFalse_WhenUserHasNoPassword()
    {
        // Arrange
        var user = new User();

        // Act
        var result = await _sut.HasPasswordAsync(user, CancellationToken.None);

        // Assert
        result.Should().BeFalse();
    }

    [Fact]
    public async Task HasPasswordAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.HasPasswordAsync(null!, CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }
    //
    [Fact]
    public async Task RemoveFromRoleAsync_ShouldRemoveRole_WhenUserAndRoleExist()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "removerole",
            NormalizedUserName = "REMOVEROLE",
            Email = "remove@example.com",
            NormalizedEmail = "REMOVE@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        await _sut.CreateAsync(user, CancellationToken.None);
        await _sut.AddToRoleAsync(user, "Admin", CancellationToken.None);
        await _sut.UpdateAsync(user, CancellationToken.None);

        // Act
        await _sut.RemoveFromRoleAsync(user, "Admin", CancellationToken.None);
        await _sut.UpdateAsync(user, CancellationToken.None);

        // Assert
        var roles = await _sut.GetRolesAsync(user, CancellationToken.None);
        roles.Should().NotContain("Admin");
    }

    [Fact]
    public async Task RemoveFromRoleAsync_ShouldDoNothing_WhenRoleDoesNotExistForUser()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "removerole2",
            NormalizedUserName = "REMOVEROLE2",
            Email = "remove2@example.com",
            NormalizedEmail = "REMOVE2@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        await _sut.CreateAsync(user, CancellationToken.None);

        // Act
        // Trying to remove a role that wasn't added
        await _sut.RemoveFromRoleAsync(user, "Admin", CancellationToken.None);
        await _sut.UpdateAsync(user, CancellationToken.None);

        // Assert
        var roles = await _sut.GetRolesAsync(user, CancellationToken.None);
        roles.Should().BeEmpty();
    }

    [Fact]
    public async Task IsInRoleAsync_ShouldReturnTrue_WhenUserIsInRole()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "inrole",
            NormalizedUserName = "INROLE",
            Email = "inrole@example.com",
            NormalizedEmail = "INROLE@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        await _sut.CreateAsync(user, CancellationToken.None);
        await _sut.AddToRoleAsync(user, "Admin", CancellationToken.None);
        await _sut.UpdateAsync(user, CancellationToken.None);

        // Act
        var result = await _sut.IsInRoleAsync(user, "Admin", CancellationToken.None);

        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public async Task IsInRoleAsync_ShouldReturnFalse_WhenUserIsNotInRole()
    {
        // Arrange
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "notinrole",
            NormalizedUserName = "NOTINROLE",
            Email = "notinrole@example.com",
            NormalizedEmail = "NOTINROLE@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        await _sut.CreateAsync(user, CancellationToken.None);

        // Act
        var result = await _sut.IsInRoleAsync(user, "Admin", CancellationToken.None);

        // Assert
        result.Should().BeFalse();
    }

    [Fact]
    public async Task GetUsersInRoleAsync_ShouldReturnUsers_WhenRoleExists()
    {
        // Arrange
        var user1 = new User
        {
            Id = Guid.NewGuid(),
            UserName = "user1",
            NormalizedUserName = "USER1",
            Email = "u1@example.com",
            NormalizedEmail = "U1@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
        var user2 = new User
        {
            Id = Guid.NewGuid(),
            UserName = "user2",
            NormalizedUserName = "USER2",
            Email = "u2@example.com",
            NormalizedEmail = "U2@EXAMPLE.COM",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        await _sut.CreateAsync(user1, CancellationToken.None);
        await _sut.CreateAsync(user2, CancellationToken.None);

        await _sut.AddToRoleAsync(user1, "Admin", CancellationToken.None);
        await _sut.AddToRoleAsync(user2, "Admin", CancellationToken.None);

        await _sut.UpdateAsync(user1, CancellationToken.None);
        await _sut.UpdateAsync(user2, CancellationToken.None);

        // Act
        var users = await _sut.GetUsersInRoleAsync("Admin", CancellationToken.None);

        // Assert
        users.Should().Contain(u => u.Id == user1.Id);
        users.Should().Contain(u => u.Id == user2.Id);
    }

    [Fact]
    public async Task GetUsersInRoleAsync_ShouldReturnEmptyList_WhenRoleHasNoUsers()
    {
        // Act
        var users = await _sut.GetUsersInRoleAsync("User", CancellationToken.None); // Assuming 'User' role is empty for this test context or newly created/seeded but empty here

        // Assert
        // The seeded 'User' role might have users if other tests ran? 
        // No, fresh container for class? Yes, IAsyncLifetime implies new container per test class instance... 
        // Wait, IAsyncLifetime in XUnit means InitializeAsync is called relative to the *test instance*.
        // But the container field is static? No, it's instance field: `private readonly PostgreSqlContainer _dbContainer`.
        // So a new container per test class instance.
        // XUnit creates a new instance of the test class for *each test method*.
        // So yes, fresh DB for each test method.
        // So 'User' role is empty.
        users.Should().BeEmpty();
    }
    //
    [Fact]
    public async Task SetEmailAsync_ShouldSetEmail_WhenUserIsValid()
    {
        // Arrange
        var user = new User();

        // Act
        await _sut.SetEmailAsync(user, "new@example.com", CancellationToken.None);

        // Assert
        user.Email.Should().Be("new@example.com");
    }

    [Fact]
    public async Task SetEmailAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.SetEmailAsync(null!, "new@example.com", CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task GetEmailAsync_ShouldReturnEmail_WhenUserIsValid()
    {
        // Arrange
        var user = new User { Email = "test@example.com" };

        // Act
        var result = await _sut.GetEmailAsync(user, CancellationToken.None);

        // Assert
        result.Should().Be("test@example.com");
    }

    [Fact]
    public async Task GetEmailAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.GetEmailAsync(null!, CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task GetEmailConfirmedAsync_ShouldReturnStatus_WhenUserIsValid()
    {
        // Arrange
        var user = new User { EmailConfirmed = true };

        // Act
        var result = await _sut.GetEmailConfirmedAsync(user, CancellationToken.None);

        // Assert
        result.Should().BeTrue();
    }

    [Fact]
    public async Task GetEmailConfirmedAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.GetEmailConfirmedAsync(null!, CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task SetEmailConfirmedAsync_ShouldSetStatus_WhenUserIsValid()
    {
        // Arrange
        var user = new User();

        // Act
        await _sut.SetEmailConfirmedAsync(user, true, CancellationToken.None);

        // Assert
        user.EmailConfirmed.Should().BeTrue();
    }

    [Fact]
    public async Task SetEmailConfirmedAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.SetEmailConfirmedAsync(null!, true, CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task GetNormalizedEmailAsync_ShouldReturnNormalizedEmail_WhenUserIsValid()
    {
        // Arrange
        var user = new User { NormalizedEmail = "TEST@EXAMPLE.COM" };

        // Act
        var result = await _sut.GetNormalizedEmailAsync(user, CancellationToken.None);

        // Assert
        result.Should().Be("TEST@EXAMPLE.COM");
    }

    [Fact]
    public async Task GetNormalizedEmailAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.GetNormalizedEmailAsync(null!, CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }

    [Fact]
    public async Task SetNormalizedEmailAsync_ShouldSetNormalizedEmail_WhenUserIsValid()
    {
        // Arrange
        var user = new User();

        // Act
        await _sut.SetNormalizedEmailAsync(user, "TEST@EXAMPLE.COM", CancellationToken.None);

        // Assert
        user.NormalizedEmail.Should().Be("TEST@EXAMPLE.COM");
    }

    [Fact]
    public async Task SetNormalizedEmailAsync_ShouldThrowException_WhenUserIsNull()
    {
        // Act
        var act = async () => await _sut.SetNormalizedEmailAsync(null!, "TEST@EXAMPLE.COM", CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<ArgumentNullException>();
    }
}
