using Dapper;
using FluentAssertions;
using Microsoft.Extensions.Options;
using Npgsql;
using SQB.Auth.Domain.Entities;
using SQB.Auth.Domain.Models;
using SQB.Auth.Infrastructure.Repositories;
using SQB.Shared;
using Testcontainers.PostgreSql;

namespace SQB.Auth.Tests;

public class RefreshTokenRepositoryTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _dbContainer = new PostgreSqlBuilder()
        .WithImage("postgres:15-alpine")
        .Build();

    private RefreshTokenRepository _sut;
    private string _connectionString;

    public async Task InitializeAsync()
    {
        await _dbContainer.StartAsync();
        _connectionString = _dbContainer.GetConnectionString();

        var options = Options.Create(new IdentityStoreOptions { ConnectionString = _connectionString });
        _sut = new RefreshTokenRepository(options);

        await InitializeDatabaseAsync();
    }

    public async Task DisposeAsync()
    {
        await _dbContainer.DisposeAsync();
    }

    private async Task InitializeDatabaseAsync()
    {
        const string ddl = """
            -------------------- users --------------------
            create table Users
            (
                Id                     uuid not null
                    constraint pk_users
                        primary key,
                UserName              varchar(256),
                NormalizedUserName   varchar(256),
                Email                  varchar(150)             not null,
                NormalizedEmail       varchar(256),
                EmailConfirmed        boolean                  not null,
                PasswordHash          text,
                SecurityStamp         text,
                ConcurrencyStamp      text,    
                PhoneNumber           varchar(30),
                PhoneNumberConfirmed boolean,
                TwoFactorEnabled     boolean                  not null,
                LockoutEnd            timestamp with time zone,
                LockoutEnabled        boolean                  not null,
                AccessFailedCount    integer                  not null,
                CreatedAt             timestamp with time zone not null,
                UpdatedAt             timestamp with time zone not null
            );

            create index email_index
                on Users (NormalizedEmail);

            create unique index user_name_index
                on Users (NormalizedUserName);

            ------------------refresh-tokens--------------------
            create table RefreshTokens
            (
                Id integer generated by default as identity
                    constraint pk_refresh_tokens
                        primary key,
                Token text                                      not null,
                Expires timestamp with time zone                not null,
                CreatedAt timestamp with time zone             not null,
                CreatedByIp text                              not null,
                Revoked timestamp with time zone,
                RevokedByIp text,
                ReplacedByToken text,
                UserId uuid not null
                    constraint fk_refresh_tokens_users
                        references Users(Id)
                        on delete cascade
            );

            create unique index ix_refresh_tokens_token
                on RefreshTokens(Token);
            """;

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync();
        await connection.ExecuteAsync(ddl);
    }

    private async Task<User> CreateUserAsync()
    {
        var user = new User
        {
            Id = Guid.NewGuid(),
            UserName = "testuser",
            NormalizedUserName = "TESTUSER",
            Email = "test@example.com",
            NormalizedEmail = "TEST@EXAMPLE.COM",
            EmailConfirmed = true,
            SecurityStamp = "stamp",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow,
            TwoFactorEnabled = false,
            LockoutEnabled = true,
            AccessFailedCount = 0
        };

        const string sql = """
            insert into Users (Id, UserName, NormalizedUserName, Email, NormalizedEmail, EmailConfirmed, 
                               SecurityStamp, CreatedAt, UpdatedAt, TwoFactorEnabled, LockoutEnabled, AccessFailedCount)
            values (@Id, @UserName, @NormalizedUserName, @Email, @NormalizedEmail, @EmailConfirmed, 
                    @SecurityStamp, @CreatedAt, @UpdatedAt, @TwoFactorEnabled, @LockoutEnabled, @AccessFailedCount)
            """;

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.ExecuteAsync(sql, user);

        return user;
    }

    [Fact]
    public async Task AddRefreshTokenAsync_ShouldAddToken_WhenValid()
    {
        // Arrange
        var user = await CreateUserAsync();
        var refreshToken = new RefreshToken
        {
            Token = "some-token",
            Expires = DateTime.UtcNow.AddDays(7),
            CreatedAt = DateTime.UtcNow,
            CreatedByIp = "127.0.0.1",
            UserId = user.Id
        };

        // Act
        var result = await _sut.AddRefreshTokenAsync(refreshToken, CancellationToken.None);

        // Assert
        result.IsSuccess.Should().BeTrue();

        // Verify in DB
        await using var connection = new NpgsqlConnection(_connectionString);
        var dbToken = await connection.QuerySingleOrDefaultAsync<RefreshToken>(
            "select * from RefreshTokens where Token = @Token", new { Token = refreshToken.Token });

        dbToken.Should().NotBeNull();
        dbToken.Token.Should().Be(refreshToken.Token);
        dbToken.UserId.Should().Be(user.Id);
    }

    [Fact]
    public async Task AddRefreshTokenAsync_ShouldFail_WhenUserDoesNotExist()
    {
        // Arrange
        var refreshToken = new RefreshToken
        {
            Token = "some-token",
            Expires = DateTime.UtcNow.AddDays(7),
            CreatedAt = DateTime.UtcNow,
            CreatedByIp = "127.0.0.1",
            UserId = Guid.NewGuid() // Non-existent user
        };

        // Act
        var result = await _sut.AddRefreshTokenAsync(refreshToken, CancellationToken.None);

        // Assert
        result.Failure.Should().BeTrue();
        result.Error.Should().Contain("DB error");
    }

    [Fact]
    public async Task GetRefreshTokenByValueAsync_ShouldReturnToken_WhenExists()
    {
        // Arrange
        var user = await CreateUserAsync();
        var tempToken = new RefreshToken
        {
            Token = "existing-token",
            Expires = DateTime.UtcNow.AddDays(7),
            CreatedAt = DateTime.UtcNow,
            CreatedByIp = "127.0.0.1",
            UserId = user.Id
        };
        await _sut.AddRefreshTokenAsync(tempToken, CancellationToken.None);

        // Act
        var result = await _sut.GetRefreshTokenByValueAsync("existing-token", CancellationToken.None);

        // Assert
        result.IsSuccess.Should().BeTrue();
        result.Value.Should().NotBeNull();
        result.Value.Token.Should().Be("existing-token");
    }

    [Fact]
    public async Task GetRefreshTokenByValueAsync_ShouldFail_WhenTokenDoesNotExist()
    {
        // Act
        var result = await _sut.GetRefreshTokenByValueAsync("non-existent-token", CancellationToken.None);

        // Assert
        result.Failure.Should().BeTrue();
        result.Error.Should().Be("No such token");
    }

    [Fact]
    public async Task RevokeRefreshTokenByValueAsync_ShouldRevokeToken_WhenExists()
    {
        // Arrange
        var user = await CreateUserAsync();
        var token = new RefreshToken
        {
            Token = "token-to-revoke",
            Expires = DateTime.UtcNow.AddDays(7),
            CreatedAt = DateTime.UtcNow,
            CreatedByIp = "127.0.0.1",
            UserId = user.Id
        };
        await _sut.AddRefreshTokenAsync(token, CancellationToken.None);

        token.Revoked = DateTime.UtcNow;
        token.RevokedByIp = "1.2.3.4";
        token.ReplacedByToken = "new-token";

        // Act
        var result = await _sut.RevokeRefreshTokenByValueAsync(token, CancellationToken.None);

        // Assert
        result.IsSuccess.Should().BeTrue();

        // Verify
        await using var connection = new NpgsqlConnection(_connectionString);
        var dbToken = await connection.QuerySingleAsync<RefreshToken>(
            "select * from RefreshTokens where Token = @Token", new { Token = token.Token });

        dbToken.Revoked.Should().BeCloseTo(token.Revoked.Value, TimeSpan.FromSeconds(1));
        dbToken.RevokedByIp.Should().Be(token.RevokedByIp);
        dbToken.ReplacedByToken.Should().Be(token.ReplacedByToken);
    }

    [Fact]
    public async Task RevokeTokenFamilyAsync_ShouldRevokeAllTokensForUser()
    {
        // Arrange
        var user = await CreateUserAsync();
        var token1 = new RefreshToken
        {
            Token = "token-1",
            Expires = DateTime.UtcNow.AddDays(7),
            CreatedAt = DateTime.UtcNow,
            CreatedByIp = "127.0.0.1",
            UserId = user.Id
        };
        var token2 = new RefreshToken
        {
            Token = "token-2",
            Expires = DateTime.UtcNow.AddDays(7),
            CreatedAt = DateTime.UtcNow,
            CreatedByIp = "127.0.0.1",
            UserId = user.Id
        };

        await _sut.AddRefreshTokenAsync(token1, CancellationToken.None);
        await _sut.AddRefreshTokenAsync(token2, CancellationToken.None);

        var revokedTime = DateTime.UtcNow;
        var revokedByIp = "10.0.0.1";

        // Act
        var result = await _sut.RevokeTokenFamilyAsync(user.Id, revokedTime, revokedByIp, CancellationToken.None);

        // Assert
        result.IsSuccess.Should().BeTrue();

        // Verify
        await using var connection = new NpgsqlConnection(_connectionString);
        var tokens = await connection.QueryAsync<RefreshToken>(
            "select * from RefreshTokens where UserId = @UserId", new { UserId = user.Id });

        tokens.Should().HaveCount(2);
        foreach (var t in tokens)
        {
            t.Revoked.Should().BeCloseTo(revokedTime, TimeSpan.FromSeconds(1));
            t.RevokedByIp.Should().Be(revokedByIp);
        }
    }

    [Fact]
    public async Task AddRefreshTokenWithRevocationAsync_ShouldAddAndRevoke_WhenValid()
    {
        // Arrange
        var user = await CreateUserAsync();
        var oldToken = new RefreshToken
        {
            Token = "old-token",
            Expires = DateTime.UtcNow.AddDays(7),
            CreatedAt = DateTime.UtcNow,
            CreatedByIp = "127.0.0.1",
            UserId = user.Id
        };
        await _sut.AddRefreshTokenAsync(oldToken, CancellationToken.None);

        // Fetch it back to get the ID which is generated by Identity (Db)
        await using var connection = new NpgsqlConnection(_connectionString);
        var dbOldToken = await connection.QuerySingleAsync<RefreshToken>(
            "select * from RefreshTokens where Token = @Token", new { Token = oldToken.Token });

        // Prepare data for call
        dbOldToken.Revoked = DateTime.UtcNow;
        dbOldToken.RevokedByIp = "1.1.1.1";
        // ReplacedByToken is set in the repo method via sql param from new token?
        // Wait, repo method:
        // Update RefreshTokens set ... ReplacedByToken = @ReplacedByToken where Id = @OldRTId
        // And params: ReplacedByToken = newRefreshToken.Token

        var newToken = new RefreshToken
        {
            Token = "new-token",
            Expires = DateTime.UtcNow.AddDays(7),
            CreatedAt = DateTime.UtcNow,
            CreatedByIp = "127.0.0.1",
            UserId = user.Id
        };

        // Act
        // Note: The method signature is (RefreshToken newRefreshToken, RefreshToken oldRefreshtoken, CancellationToken ct)
        // It uses oldRefreshToken properties for the update: Revoked, RevokedByIp, Id.
        var result = await _sut.AddRefreshTokenWithRevocationAsync(newToken, dbOldToken, CancellationToken.None);

        // Assert
        result.IsSuccess.Should().BeTrue();

        // Verify
        var dbTokens = await connection.QueryAsync<RefreshToken>(
            "select * from RefreshTokens where UserId = @UserId order by CreatedAt", new { UserId = user.Id });

        dbTokens.Should().HaveCount(2);

        var oldT = dbTokens.First(t => t.Token == "old-token");
        var newT = dbTokens.First(t => t.Token == "new-token");

        oldT.Revoked.Should().BeCloseTo(dbOldToken.Revoked.Value, TimeSpan.FromSeconds(1));
        oldT.ReplacedByToken.Should().Be("new-token");

        newT.Revoked.Should().BeNull();
    }
}
