-------------------- users --------------------
create table Users
(
    Id                      uuid not null
        constraint pk_users
            primary key,
    UserName                varchar(256),
    NormalizedUserName      varchar(256),
    Email                   varchar(150)             not null,
    NormalizedEmail         varchar(256),
    EmailConfirmed          boolean                  not null,
    PasswordHash            text,
    SecurityStamp           text,
    ConcurrencyStamp        text,
    PhoneNumber             varchar(30),
    PhoneNumberConfirmed    boolean,
    TwoFactorEnabled        boolean                  not null,
    LockoutEnd              timestamp with time zone,
    LockoutEnabled          boolean                  not null,
    AccessFailedCount       integer                  not null,
    CreatedAt               timestamp with time zone not null,
    UpdatedAt               timestamp with time zone not null
);

alter table Users
    owner to administrator;

create index email_index
    on Users (NormalizedEmail);

create unique index user_name_index
    on Users (NormalizedUserName);

-------------------- roles --------------------
create table Roles
(
    Id                      integer generated by default as identity
        constraint pk_roles
            primary key,
    Name                    varchar(256),
    NormalizedName          varchar(256),
    ConcurrencyStamp        text
);

alter table Roles
    owner to administrator;

create unique index role_name_index
    on Roles (NormalizedName);

-------------------- user roles --------------------
create table UserRoles
(
    UserId uuid not null
        constraint fk_user_roles_users_user_id
            references Users
            on delete cascade,
    RoleId integer not null
        constraint fk_user_roles_roles_role_id
            references Roles
            on delete cascade,
    constraint pk_user_roles
        primary key (UserId, RoleId)
);

alter table UserRoles
    owner to administrator;

create index ix_user_roles_role_id
    on UserRoles (RoleId);

------------------refresh-tokens--------------------
create table RefreshTokens
(
    Id integer generated by default as identity
        constraint pk_refresh_tokens
            primary key,
    Token                   text                              not null,
    Expires                 timestamp with time zone          not null,
    CreatedAt               timestamp with time zone          not null,
    CreatedByIp             text                              not null,
    Revoked                 timestamp with time zone,
    RevokedByIp             text,
    ReplacedByToken         text,
    UserId                  uuid                              not null
        constraint fk_refresh_tokens_users
            references Users
            on delete cascade
);

alter table RefreshTokens
    owner to administrator;

create unique index ix_refresh_tokens_token
    on RefreshTokens(Token);

create index ix_refresh_tokens_user_id
    on RefreshTokens (UserId);
