-------------------- users --------------------
create table users
(
    id                     uuid not null
        constraint pk_users
            primary key,
    user_name              varchar(256),
    normalized_user_name   varchar(256),
    email                  varchar(150)             not null,
    normalized_email       varchar(256),
    email_confirmed        boolean                  not null,
    password_hash          text,
    security_stamp         text,
    concurrency_stamp      text,
    phone_number           varchar(30)              not null,
    phone_number_confirmed boolean                  not null,
    two_factor_enabled     boolean                  not null,
    lockout_end            timestamp with time zone,
    lockout_enabled        boolean                  not null,
    access_failed_count    integer                  not null,
    created_at             timestamp with time zone not null,
    updated_at             timestamp with time zone not null,
);

alter table users
    owner to administrator;

create index email_index
    on users (normalized_email);

create unique index user_name_index
    on users (normalized_user_name);

-------------------- roles --------------------
create table roles
(
    id                integer generated by default as identity
        constraint pk_roles
            primary key,
    name              varchar(256),
    normalized_name   varchar(256),
    concurrency_stamp text
);

alter table roles
    owner to administrator;

create unique index role_name_index
    on roles (normalized_name);

-------------------- user roles --------------------
create table user_roles
(
    user_id integer not null
        constraint fk_user_roles_users_user_id
            references users
            on delete cascade,
    role_id integer not null
        constraint fk_user_roles_roles_role_id
            references roles
            on delete cascade,
    constraint pk_user_roles
        primary key (user_id, role_id)
);

alter table user_roles
    owner to administrator;

create index ix_user_roles_role_id
    on user_roles (role_id);
