<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>SQB.Auth.Domain</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.11.7"/>
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.0"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11"/>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\SQB.Shared\SQB.Shared.csproj"/>
    </ItemGroup>
</Project>
