<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>SQB.ApiGateway</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="Logging\**"/>
        <Content Remove="Logging\**"/>
        <EmbeddedResource Remove="Logging\**"/>
        <None Remove="Logging\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11"/>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.11.7"/>
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.0"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0"/>

        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10"/>
        <PackageReference Include="MMLib.SwaggerForOcelot" Version="8.3.2"/>
        <PackageReference Include="Ocelot" Version="23.3.4"/>
    </ItemGroup>

</Project>
