<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>SQB.Auth.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
        <HintPath>..\..\..\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\10.0.1\lib\net8.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SQB.Auth.Domain\SQB.Auth.Domain.csproj" />
      <ProjectReference Include="..\SQB.Auth.Infrastructure\SQB.Auth.Infrastructure.csproj" />
      <ProjectReference Include="..\SQB.Shared\SQB.Shared.csproj" />
    </ItemGroup>

</Project>
